services:
  bot:
    build:
      context: ./bot
      dockerfile: bot.dockerfile
    environment:
      DISCORD_SECRETS_FILE: /run/secrets/discord_secrets
    secrets:
      - discord_secrets
    volumes:
      - db:/home/bot/db
  auth:
    build:
      context: ./auth
      dockerfile: auth.dockerfile
    ports:
      - 8000:8000
    environment:
      AUTH_SECRETS_FILE: /run/secrets/auth_secrets
    secrets:
      - auth_secrets
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379
volumes:
  db:
secrets:
  discord_secrets:
    file: ./bot/.env
  auth_secrets:
    file: ./auth/.env
  